# Generated by Django 3.1.7 on 2021-03-29 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0002_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkboxlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listname', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='search',
            name='userid',
        ),
        migrations.AddField(
            model_name='search',
            name='user_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='searchapp.user'),
        ),
    ]
